### ISSUE TITLE
has_many associations doesn't work

### ISSUE THREAD

**Issue by onlinetocode** [devmynd/jsonb_accessor#34]
HI there,
I tried to use jsonb_accessor for associations. While belongs_to works seamlessly, has_many shows an error.

I tried it with Rails 4.2.3 and Rails 4.2.4. On jsonb_accessor side I use the latest 0.3.1.

I've got this Setup:
```ruby
class City < ActiveRecord::Base
	has_many :streets
end
```
```ruby
class Street < ActiveRecord::Base
  belongs_to :city
  jsonb_accessor(
    # jsonb column:
    :street_details,
    # data fields:
    city_id: :integer
  )
end
```
When I run `Street.first.City` everything works fine:
```
Street.first.city
  Street Load (0.8ms)  SELECT  "streets".* FROM "streets"  ORDER BY "streets"."id" ASC LIMIT 1
  City Load (0.4ms)  SELECT  "cities".* FROM "cities" WHERE "cities"."id" = $1 LIMIT 1  [["id", 1]]
 => #<City id: 1, name: "Berlin", created_at: "2015-11-11 15:02:35", updated_at: "2015-11-11 15:02:35"> 
```

But when I use the `has_many` association via `City.first.streets` I get this error:

```
City.first.streets
  City Load (2.6ms)  SELECT  "cities".* FROM "cities"  ORDER BY "cities"."id" ASC LIMIT 1
PG::UndefinedColumn: ERROR:  column streets.city_id does not exist
LINE 1: SELECT "streets".* FROM "streets" WHERE "streets"."city_id" ...
                                                ^
: SELECT "streets".* FROM "streets" WHERE "streets"."city_id" = $1
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column streets.city_id does not exist
LINE 1: SELECT "streets".* FROM "streets" WHERE "streets"."city_id" ...
                                                ^
: SELECT "streets".* FROM "streets" WHERE "streets"."city_id" = $1
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:641:in `prepare'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:641:in `prepare_statement'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:600:in `exec_cache'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:589:in `execute_and_clear'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:351:in `select'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/querying.rb:39:in `find_by_sql'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/statement_cache.rb:107:in `execute'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:451:in `get_records'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:455:in `find_target'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_association.rb:392:in `load_target'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_proxy.rb:45:in `load_target'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/associations/collection_proxy.rb:945:in `to_ary'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.3/lib/active_record/relation.rb:629:in `inspect'
... 1 levels...
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/mauricekock/rails/test_apps/jsonb_test/bin/rails:8:in `<top (required)>'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/mauricekock/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/mauricekock/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/mauricekock/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

Here is a sample application in case it is needed:
https://github.com/onlinetocode/jsonb_test

There is a migration which creates a city and two streets.

**Comment by crismali** [comment]
This appears to be related to issues with using virtual attributes in ActiveRecord (mentioned in #33) but it looks like there's something else wrong here.

**Comment by jhirn** [comment]
Hi @onlinetocode. 

Overriding belongs_to so it supports attributes stored in the json column would add quite a bit of complexity, particularly when considering eager_loading. Can you give me some other use cases where you wish to use associations on json attributes? 

It feels like if something `belongs_to` something else it would be better to use a real column. In your case above, you could also add `def city...` on your street class so that `Street.first.city` would work. 

I'm open to more discussion or a PR on how to support associations, but we don't state support for associations so I'm closing this a a bug for now.

**Comment by onlinetocode** [comment]
Hi @jhirn,
thank you very much for your explanation. 

`belongs_to` works seamless. So `Street.first.city` works out of the box.

```
Street.first.city
  Street Load (0.8ms)  SELECT  "streets".* FROM "streets"  ORDER BY "streets"."id" ASC LIMIT 1
  City Load (0.4ms)  SELECT  "cities".* FROM "cities" WHERE "cities"."id" = $1 LIMIT 1  [["id", 1]]
 => #<City id: 1, name: "Berlin", created_at: "2015-11-11 15:02:35", updated_at: "2015-11-11 15:02:35"> 
```

Only the other way around doesn't work. The `has_many` association does not work. e.g. "a city has several requests" is throwing the error.

But this was more or less an example case to make a simple example app out of it. 

I tried to use this gem to create an general business process model with the help of STI and a jsonb column. I thought I could build processes in one table where each process could have associations with a lot of different models and not polute my database with a lot of different business process tables. For example invoice releases (with associations to an invoice, to a requestor and to an approver) or requests for holiday replacements (with associations to a co worker for replacement, to an requestor and to an approver). But I understand that this is a requirement which jsonb_accessors is not intended and not (yet) ready for. I just wanted to make sure that I'm not missing something out.

**Comment by jhirn** [comment]
I appreciate the feedback. Hopefully the gem is providing usefulness in some ways for you. The concept was invented to avoid sparse columns in STI so that's definitely a great use case. 

I'd also be open to considering a separate has_many macro which might get us halfway there without stomping on AR's implementation and explicitly calling attention to limitations.
