### ISSUE TITLE
Support for pg 1.0.0 gem

### ISSUE THREAD

**Issue by marclennox** [devmynd/jsonb_accessor#93]
I think that with the recent release of pg-1.0.0, jsonb_accessor is incompatible.

```
/usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:404:in `block (2 levels) in replace_gem': can't activate pg (~> 0.18), already activated pg-1.0.0. Make sure all dependencies are added to Gemfile. (Gem::LoadError)
	from /usr/local/lib/ruby/bundler/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/bundler/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /usr/local/lib/ruby/bundler/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
	from /usr/local/lib/ruby/bundler/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /usr/local/lib/ruby/bundler/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
	from /usr/local/lib/ruby/bundler/gems/jsonb_accessor-1.0.0/lib/jsonb_accessor.rb:5:in `<top (required)>'
	from /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
	from /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
	from /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
	from /usr/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
	from /usr/src/app/config/application.rb:17:in `<top (required)>'
	from /usr/local/lib/ruby/bundler/gems/railties-5.1.4/lib/rails/command/actions.rb:15:in `require'
	from /usr/local/lib/ruby/bundler/gems/railties-5.1.4/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /usr/local/lib/ruby/bundler/gems/railties-5.1.4/lib/rails/commands/console/console_command.rb:96:in `perform'
	from /usr/local/lib/ruby/bundler/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/bundler/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/bundler/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/lib/ruby/bundler/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
	from /usr/local/lib/ruby/bundler/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
	from /usr/local/lib/ruby/bundler/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

**Comment by kshnurov** [comment]
This is a rails issue: https://github.com/rails/rails/pull/31671

**Comment by marclennox** [comment]
ok thank you.
